### PR TITLE
try to fix #45

### LINKED ISSUE #45: Screen stuck after $stateChangeStart is defaultPrevent'ed
Consider the following scenario:
1. User leaves the state, either by going back or to another state.
2. To confirm state change, I call `preventDefault` on $stateChangeStart event.
3. Continue state change after confirmation.

I guess there's a issue with ionic-native-transitions because after event's prevented, the screen gets stuck until `executePendingTransition` is called manually. At least this is what I get on iOS 9.1 with platform 3.9.2 and cordova-plugin-wkwebview.

### PR DESCRIPTION
**Pull request by Klaster1**
This adds additional check for prevented $stateChangeStart event. If the check succeeds, abort everything and don't initiate transition, because it was actually cancelled.

### CODE REVIEW

**Comment by shprink** [comment]
Great stuff @Klaster1 :) Thanks very much! I am going to release a new version

**Comment by Klaster1** [comment]
By the way, state events are deprecated in uirouter 1.0 and replaced by
extensible hooks, so you might want to keep that in mind if ionic devs
decide to use the new release.

**Comment by shprink** [comment]
Good to know thanks! I guess the ionic team won't upgrade, but I am gonna ask :)

**Comment by shprink** [comment]
Rc6 with your fix is released.

**Pull request merged**
