### PR TITLE
Adding bower file

### PR DESCRIPTION
**Pull request by leobetosouza**
Adding a JSON file with metadata for Bower

### CODE REVIEW

**Comment by shprink** [comment]
Awesome! Do I need to publish to bower's repo the same way I do for npm: `npm publish` ?

**Comment by leobetosouza** [comment]
I never published a bower package.

This page explains how: http://bower.io/docs/creating-packages/

There's a example: `bower register <my-package-name> <git-endpoint>`

I'm using ionic-native-transitions from my bower.json pointing to my fork because my project needs the bower.json to know the plugin mainfile: `"ionic-native-transitions": "leobetosouza/ionic-native-transitions#~1.0.0-beta6"`

**Comment by shprink** [comment]
@there you go @leobetosouza thanks for doing this :) BTW if you run android you should upgrade telerik's plugin to 0.5.2. it is not perfect but at least it does not crash with crosswalk anymore.

**Comment by leobetosouza** [comment]
thank you! i am not using crosswalk now... no crashes yet :)

**Pull request merged**
