### PR TITLE
Allow transition to same state with different params

### PR DESCRIPTION
**Pull request by kenmickles**
* Use $state.is() instead of comparing against name in same state check
* Rebuild dist files

### CODE REVIEW

**Comment by shprink** [comment]
why using `.is` over something else? BTW cannot merge that.

**Comment by TomSeldon** [comment]
Was about to open a PR to do the same thing.

> why using .is over something else?

Currently as state transitions to states with the same name are blocked, the following example will not work:

```javascript
$ionicNativeTransitions.stateGo('detail', {
    id: 1
});

// At a later point from within the `detail` state

$ionicNativeTransitions.stateGo('detail', {
    id: 2
});
```

That will be blocked as only the state name is checked, but that's clearly a bug as we're specifying a different ID for the view.

As this PR seems to have gone a bit stale I'd be happy to open a new one without the conflicts.

**Comment by shprink** [comment]
you are right, please do @TomSeldon  👍  thanks very much.

**Comment by shprink** [comment]
no need to commit the dist files. I will build after the merge and release a new version

**Comment by TomSeldon** [comment]
Ok great, will get a PR up now 👍

**Comment by TomSeldon** [comment]
Addressed in https://github.com/shprink/ionic-native-transitions/pull/126

**Pull request closed without merging**
